version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
#      POSTGRES_PASSWORD: "1234"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - /tmp/database:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080